In [1]:
import pymongo
import pandas as pd

In [6]:
df = pd.read_csv('mtcars.csv')
df.sample(10)

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [45]:
print(df['model'][1])

Mazda RX4 Wag

In [8]:
x=0
while x != len(df):
    print(df['model'][x] ,df['mpg'][x],df['cyl'][x],df['disp'][x],df['hp'][x],df['drat'][x],df['wt'][x],df['qsec'][x],df['vs'][x],df['am'][x],df['gear'][x],df['carb'][x])
    x+=1

Mazda RX4 21.0 6 160.0 110 3.9 2.62 16.46 0 1 4 4
Mazda RX4 Wag 21.0 6 160.0 110 3.9 2.875 17.02 0 1 4 4
Datsun 710 22.8 4 108.0 93 3.85 2.32 18.61 1 1 4 1
Hornet 4 Drive 21.4 6 258.0 110 3.08 3.215 19.44 1 0 3 1
Hornet Sportabout 18.7 8 360.0 175 3.15 3.44 17.02 0 0 3 2
Valiant 18.1 6 225.0 105 2.76 3.46 20.22 1 0 3 1
Duster 360 14.3 8 360.0 245 3.21 3.57 15.84 0 0 3 4
Merc 240D 24.4 4 146.7 62 3.69 3.19 20.0 1 0 4 2
Merc 230 22.8 4 140.8 95 3.92 3.15 22.9 1 0 4 2
Merc 280 19.2 6 167.6 123 3.92 3.44 18.3 1 0 4 4
Merc 280C 17.8 6 167.6 123 3.92 3.44 18.9 1 0 4 4
Merc 450SE 16.4 8 275.8 180 3.07 4.07 17.4 0 0 3 3
Merc 450SL 17.3 8 275.8 180 3.07 3.73 17.6 0 0 3 3
Merc 450SLC 15.2 8 275.8 180 3.07 3.78 18.0 0 0 3 3
Cadillac Fleetwood 10.4 8 472.0 205 2.93 5.25 17.98 0 0 3 4
Lincoln Continental 10.4 8 460.0 215 3.0 5.424 17.82 0 0 3 4
Chrysler Imperial 14.7 8 440.0 230 3.23 5.345 17.42 0 0 3 4
Fiat 128 32.4 4 78.7 66 4.08 2.2 19.47 1 1 4 1
Honda Civic 30.4 4 75.7 52 4.93 1.615 18.52 1 1 4 2
Toyota Corolla 33.9 4 71.1 65 4.22 1.835 19.9 1 1 4 1
Toyota Corona 21.5 4 120.1 97 3.7 2.465 20.01 1 0 3 1
Dodge Challenger 15.5 8 318.0 150 2.76 3.52 16.87 0 0 3 2
AMC Javelin 15.2 8 304.0 150 3.15 3.435 17.3 0 0 3 2
Camaro Z28 13.3 8 350.0 245 3.73 3.84 15.41 0 0 3 4
Pontiac Firebird 19.2 8 400.0 175 3.08 3.845 17.05 0 0 3 2
Fiat X1-9 27.3 4 79.0 66 4.08 1.935 18.9 1 1 4 1
Porsche 914-2 26.0 4 120.3 91 4.43 2.14 16.7 0 1 5 2
Lotus Europa 30.4 4 95.1 113 3.77 1.513 16.9 1 1 5 2
Ford Pantera L 15.8 8 351.0 264 4.22 3.17 14.5 0 1 5 4
Ferrari Dino 19.7 6 145.0 175 3.62 2.77 15.5 0 1 5 6
Maserati Bora 15.0 8 301.0 335 3.54 3.57 14.6 0 1 5 8
Volvo 142E 21.4 4 121.0 109 4.11 2.78 18.6 1 1 4 2

### Mongo part (connect server)

In [2]:
client = pymongo.MongoClient('mongodb://127.0.0.1:27017/')
client

MongoClient(host=['127.0.0.1:27017'], document_class=dict, tz_aware=False, connect=True)

In [18]:
client.show

Database(MongoClient(host=['127.0.0.1:27017'], document_class=dict, tz_aware=False, connect=True), 'show')

In [3]:
mydb = client['CarModal']

In [4]:
information = mydb.CarModalInformation

In [43]:

records=[{
        'firstname':'John',
        'lastname':'Doe',
        'department':'Analytics',
        'qualification':'statistics',
        'age':35
        
        },
         {
        'firstname':'John ',
        'lastname':'Smith',
        'department':'Analytics',
        'qualification':'masters',
        'age':30
        
        },
        {
        'firstname':'Manish',
        'lastname':'Sen',
        'department':'Analytics',
        'qualification':'phd',
        'age':34
        
        },
        {
        'firstname':'Ram',
        'lastname':'Singh',
        'department':'Analytics',
        'qualification':'master',
        'age':32
        
        }]

In [46]:
records

[{'firstname': 'John',
  'lastname': 'Doe',
  'department': 'Analytics',
  'qualification': 'statistics',
  'age': 35},
 {'firstname': 'John ',
  'lastname': 'Smith',
  'department': 'Analytics',
  'qualification': 'masters',
  'age': 30},
 {'firstname': 'Manish',
  'lastname': 'Sen',
  'department': 'Analytics',
  'qualification': 'phd',
  'age': 34},
 {'firstname': 'Ram',
  'lastname': 'Singh',
  'department': 'Analytics',
  'qualification': 'master',
  'age': 32}]

In [47]:
information.insert_many(records)

In [50]:
for _ in information.find():
    print(_)

{'_id': ObjectId('60cc4853dd69706d8b9b9e18'), 'frist name': 'ravi', 'last name': 'sharma'}
{'_id': 'fsdfsdfnf', 'frist name': 'ssdf', 'last name': 'vf'}
{'_id': ObjectId('60cc59cfdd69706d8b9b9e79'), 'firstname': 'John', 'lastname': 'Doe', 'department': 'Analytics', 'qualification': 'statistics', 'age': 35}
{'_id': ObjectId('60cc59cfdd69706d8b9b9e7a'), 'firstname': 'John ', 'lastname': 'Smith', 'department': 'Analytics', 'qualification': 'masters', 'age': 30}
{'_id': ObjectId('60cc59cfdd69706d8b9b9e7b'), 'firstname': 'Manish', 'lastname': 'Sen', 'department': 'Analytics', 'qualification': 'phd', 'age': 34}
{'_id': ObjectId('60cc59cfdd69706d8b9b9e7c'), 'firstname': 'Ram', 'lastname': 'Singh', 'department': 'Analytics', 'qualification': 'master', 'age': 32}

### Using Pandas insert data

In [34]:
x=0
records = []
while x != len(df):
    record = {'Car Model ': df['model'][x],
        'Miles/(US) gallon': df['mpg'][x],
        'Number of cylinders': df['cyl'][x],
        'Displacement (cu in)': df['disp'][x],
        'Gross horsepower': df['hp'][x],
        'Rear axle ratio': df['drat'][x],
        'Weight (1000 lbs)': df['wt'][x],
        '1/4 mile time': df['qsec'][x],
        'Engine (0 = V-shaped, 1 = straight)': df['vs'][x],
        'Transmission (0 = automatic, 1 = manual)': df['am'][x],
        'Number of forward gears': df['gear'][x],
        'Number of carburetors': df['carb'][x]
        }
    records.append(record)
    
    x+=1

In [35]:
records

[{'Car Model ': 'Mazda RX4',
  'Miles/(US) gallon': 21.0,
  'Number of cylinders': 6,
  'Displacement (cu in)': 160.0,
  'Gross horsepower': 110,
  'Rear axle ratio': 3.9,
  'Weight (1000 lbs)': 2.62,
  '1/4 mile time': 16.46,
  'Engine (0 = V-shaped, 1 = straight)': 0,
  'Transmission (0 = automatic, 1 = manual)': 1,
  'Number of forward gears': 4,
  'Number of carburetors': 4},
 {'Car Model ': 'Mazda RX4 Wag',
  'Miles/(US) gallon': 21.0,
  'Number of cylinders': 6,
  'Displacement (cu in)': 160.0,
  'Gross horsepower': 110,
  'Rear axle ratio': 3.9,
  'Weight (1000 lbs)': 2.875,
  '1/4 mile time': 17.02,
  'Engine (0 = V-shaped, 1 = straight)': 0,
  'Transmission (0 = automatic, 1 = manual)': 1,
  'Number of forward gears': 4,
  'Number of carburetors': 4},
 {'Car Model ': 'Datsun 710',
  'Miles/(US) gallon': 22.8,
  'Number of cylinders': 4,
  'Displacement (cu in)': 108.0,
  'Gross horsepower': 93,
  'Rear axle ratio': 3.85,
  'Weight (1000 lbs)': 2.32,
  '1/4 mile time': 18.61,
  'Engine (0 = V-shaped, 1 = straight)': 1,
  'Transmission (0 = automatic, 1 = manual)': 1,
  'Number of forward gears': 4,
  'Number of carburetors': 1},
 {'Car Model ': 'Hornet 4 Drive',
  'Miles/(US) gallon': 21.4,
  'Number of cylinders': 6,
  'Displacement (cu in)': 258.0,
  'Gross horsepower': 110,
  'Rear axle ratio': 3.08,
  'Weight (1000 lbs)': 3.215,
  '1/4 mile time': 19.44,
  'Engine (0 = V-shaped, 1 = straight)': 1,
  'Transmission (0 = automatic, 1 = manual)': 0,
  'Number of forward gears': 3,
  'Number of carburetors': 1},
 {'Car Model ': 'Hornet Sportabout',
  'Miles/(US) gallon': 18.7,
  'Number of cylinders': 8,
  'Displacement (cu in)': 360.0,
  'Gross horsepower': 175,
  'Rear axle ratio': 3.15,
  'Weight (1000 lbs)': 3.44,
  '1/4 mile time': 17.02,
  'Engine (0 = V-shaped, 1 = straight)': 0,
  'Transmission (0 = automatic, 1 = manual)': 0,
  'Number of forward gears': 3,
  'Number of carburetors': 2},
 {'Car Model ': 'Valiant',
  'Miles/(US) gallon': 18.1,
  'Number of cylinders': 6,
  'Displacement (cu in)': 225.0,
  'Gross horsepower': 105,
  'Rear axle ratio': 2.76,
  'Weight (1000 lbs)': 3.46,
  '1/4 mile time': 20.22,
  'Engine (0 = V-shaped, 1 = straight)': 1,
  'Transmission (0 = automatic, 1 = manual)': 0,
  'Number of forward gears': 3,
  'Number of carburetors': 1},
 {'Car Model ': 'Duster 360',
  'Miles/(US) gallon': 14.3,
  'Number of cylinders': 8,
  'Displacement (cu in)': 360.0,
  'Gross horsepower': 245,
  'Rear axle ratio': 3.21,
  'Weight (1000 lbs)': 3.57,
  '1/4 mile time': 15.84,
  'Engine (0 = V-shaped, 1 = straight)': 0,
  'Transmission (0 = automatic, 1 = manual)': 0,
  'Number of forward gears': 3,
  'Number of carburetors': 4},
 {'Car Model ': 'Merc 240D',
  'Miles/(US) gallon': 24.4,
  'Number of cylinders': 4,
  'Displacement (cu in)': 146.7,
  'Gross horsepower': 62,
  'Rear axle ratio': 3.69,
  'Weight (1000 lbs)': 3.19,
  '1/4 mile time': 20.0,
  'Engine (0 = V-shaped, 1 = straight)': 1,
  'Transmission (0 = automatic, 1 = manual)': 0,
  'Number of forward gears': 4,
  'Number of carburetors': 2},
 {'Car Model ': 'Merc 230',
  'Miles/(US) gallon': 22.8,
  'Number of cylinders': 4,
  'Displacement (cu in)': 140.8,
  'Gross horsepower': 95,
  'Rear axle ratio': 3.92,
  'Weight (1000 lbs)': 3.15,
  '1/4 mile time': 22.9,
  'Engine (0 = V-shaped, 1 = straight)': 1,
  'Transmission (0 = automatic, 1 = manual)': 0,
  'Number of forward gears': 4,
  'Number of carburetors': 2},
 {'Car Model ': 'Merc 280',
  'Miles/(US) gallon': 19.2,
  'Number of cylinders': 6,
  'Displacement (cu in)': 167.6,
  'Gross horsepower': 123,
  'Rear axle ratio': 3.92,
  'Weight (1000 lbs)': 3.44,
  '1/4 mile time': 18.3,
  'Engine (0 = V-shaped, 1 = straight)': 1,
  'Transmission (0 = automatic, 1 = manual)': 0,
  'Number of forward gears': 4,
  'Number of carburetors': 4},
 {'Car Model ': 'Merc 280C',
  'Miles/(US) gallon': 17.8,
  'Number of cylinders': 6,
  'Displacement (cu in)': 167.6,
  'Gross horsepower': 123,
  'Rear axle ratio': 3.92,
  'Weight (1000 lbs)': 3.44,
  '1/4 mile time': 18.9,
  'Engine (0 = V-shaped, 1 = straight)': 1,
  'Transmission (0 = automatic, 1 = manual)': 0,
  'Number of forward gears': 4,
  'Number of carburetors': 4},
 {'Car Model ': 'Merc 450SE',
  'Miles/(US) gallon': 16.4,
  'Number of cylinders': 8,
  'Displacement (cu in)': 275.8,
  'Gross horsepower': 180,
  'Rear axle ratio': 3.07,
  'Weight (1000 lbs)': 4.07,
  '1/4 mile time': 17.4,
  'Engine (0 = V-shaped, 1 = straight)': 0,
  'Transmission (0 = automatic, 1 = manual)': 0,
  'Number of forward gears': 3,
  'Number of carburetors': 3},
 {'Car Model ': 'Merc 450SL',
  'Miles/(US) gallon': 17.3,
  'Number of cylinders': 8,
  'Displacement (cu in)': 275.8,
  'Gross horsepower': 180,
  'Rear axle ratio': 3.07,
  'Weight (1000 lbs)': 3.73,
  '1/4 mile time': 17.6,
  'Engine (0 = V-shaped, 1 = straight)': 0,
  'Transmission (0 = automatic, 1 = manual)': 0,
  'Number of forward gears': 3,
  'Number of carburetors': 3},
 {'Car Model ': 'Merc 450SLC',
  'Miles/(US) gallon': 15.2,
  'Number of cylinders': 8,
  'Displacement (cu in)': 275.8,
  'Gross horsepower': 180,
  'Rear axle ratio': 3.07,
  'Weight (1000 lbs)': 3.78,
  '1/4 mile time': 18.0,
  'Engine (0 = V-shaped, 1 = straight)': 0,
  'Transmission (0 = automatic, 1 = manual)': 0,
  'Number of forward gears': 3,
  'Number of carburetors': 3},
 {'Car Model ': 'Cadillac Fleetwood',
  'Miles/(US) gallon': 10.4,
  'Number of cylinders': 8,
  'Displacement (cu in)': 472.0,
  'Gross horsepower': 205,
  'Rear axle ratio': 2.93,
  'Weight (1000 lbs)': 5.25,
  '1/4 mile time': 17.98,
  'Engine (0 = V-shaped, 1 = straight)': 0,
  'Transmission (0 = automatic, 1 = manual)': 0,
  'Number of forward gears': 3,
  'Number of carburetors': 4},
 {'Car Model ': 'Lincoln Continental',
  'Miles/(US) gallon': 10.4,
  'Number of cylinders': 8,
  'Displacement (cu in)': 460.0,
  'Gross horsepower': 215,
  'Rear axle ratio': 3.0,
  'Weight (1000 lbs)': 5.424,
  '1/4 mile time': 17.82,
  'Engine (0 = V-shaped, 1 = straight)': 0,
  'Transmission (0 = automatic, 1 = manual)': 0,
  'Number of forward gears': 3,
  'Number of carburetors': 4},
 {'Car Model ': 'Chrysler Imperial',
  'Miles/(US) gallon': 14.7,
  'Number of cylinders': 8,
  'Displacement (cu in)': 440.0,
  'Gross horsepower': 230,
  'Rear axle ratio': 3.23,
  'Weight (1000 lbs)': 5.345,
  '1/4 mile time': 17.42,
  'Engine (0 = V-shaped, 1 = straight)': 0,
  'Transmission (0 = automatic, 1 = manual)': 0,
  'Number of forward gears': 3,
  'Number of carburetors': 4},
 {'Car Model ': 'Fiat 128',
  'Miles/(US) gallon': 32.4,
  'Number of cylinders': 4,
  'Displacement (cu in)': 78.7,
  'Gross horsepower': 66,
  'Rear axle ratio': 4.08,
  'Weight (1000 lbs)': 2.2,
  '1/4 mile time': 19.47,
  'Engine (0 = V-shaped, 1 = straight)': 1,
  'Transmission (0 = automatic, 1 = manual)': 1,
  'Number of forward gears': 4,
  'Number of carburetors': 1},
 {'Car Model ': 'Honda Civic',
  'Miles/(US) gallon': 30.4,
  'Number of cylinders': 4,
  'Displacement (cu in)': 75.7,
  'Gross horsepower': 52,
  'Rear axle ratio': 4.93,
  'Weight (1000 lbs)': 1.615,
  '1/4 mile time': 18.52,
  'Engine (0 = V-shaped, 1 = straight)': 1,
  'Transmission (0 = automatic, 1 = manual)': 1,
  'Number of forward gears': 4,
  'Number of carburetors': 2},
 {'Car Model ': 'Toyota Corolla',
  'Miles/(US) gallon': 33.9,
  'Number of cylinders': 4,
  'Displacement (cu in)': 71.1,
  'Gross horsepower': 65,
  'Rear axle ratio': 4.22,
  'Weight (1000 lbs)': 1.835,
  '1/4 mile time': 19.9,
  'Engine (0 = V-shaped, 1 = straight)': 1,
  'Transmission (0 = automatic, 1 = manual)': 1,
  'Number of forward gears': 4,
  'Number of carburetors': 1},
 {'Car Model ': 'Toyota Corona',
  'Miles/(US) gallon': 21.5,
  'Number of cylinders': 4,
  'Displacement (cu in)': 120.1,
  'Gross horsepower': 97,
  'Rear axle ratio': 3.7,
  'Weight (1000 lbs)': 2.465,
  '1/4 mile time': 20.01,
  'Engine (0 = V-shaped, 1 = straight)': 1,
  'Transmission (0 = automatic, 1 = manual)': 0,
  'Number of forward gears': 3,
  'Number of carburetors': 1},
 {'Car Model ': 'Dodge Challenger',
  'Miles/(US) gallon': 15.5,
  'Number of cylinders': 8,
  'Displacement (cu in)': 318.0,
  'Gross horsepower': 150,
  'Rear axle ratio': 2.76,
  'Weight (1000 lbs)': 3.52,
  '1/4 mile time': 16.87,
  'Engine (0 = V-shaped, 1 = straight)': 0,
  'Transmission (0 = automatic, 1 = manual)': 0,
  'Number of forward gears': 3,
  'Number of carburetors': 2},
 {'Car Model ': 'AMC Javelin',
  'Miles/(US) gallon': 15.2,
  'Number of cylinders': 8,
  'Displacement (cu in)': 304.0,
  'Gross horsepower': 150,
  'Rear axle ratio': 3.15,
  'Weight (1000 lbs)': 3.435,
  '1/4 mile time': 17.3,
  'Engine (0 = V-shaped, 1 = straight)': 0,
  'Transmission (0 = automatic, 1 = manual)': 0,
  'Number of forward gears': 3,
  'Number of carburetors': 2},
 {'Car Model ': 'Camaro Z28',
  'Miles/(US) gallon': 13.3,
  'Number of cylinders': 8,
  'Displacement (cu in)': 350.0,
  'Gross horsepower': 245,
  'Rear axle ratio': 3.73,
  'Weight (1000 lbs)': 3.84,
  '1/4 mile time': 15.41,
  'Engine (0 = V-shaped, 1 = straight)': 0,
  'Transmission (0 = automatic, 1 = manual)': 0,
  'Number of forward gears': 3,
  'Number of carburetors': 4},
 {'Car Model ': 'Pontiac Firebird',
  'Miles/(US) gallon': 19.2,
  'Number of cylinders': 8,
  'Displacement (cu in)': 400.0,
  'Gross horsepower': 175,
  'Rear axle ratio': 3.08,
  'Weight (1000 lbs)': 3.845,
  '1/4 mile time': 17.05,
  'Engine (0 = V-shaped, 1 = straight)': 0,
  'Transmission (0 = automatic, 1 = manual)': 0,
  'Number of forward gears': 3,
  'Number of carburetors': 2},
 {'Car Model ': 'Fiat X1-9',
  'Miles/(US) gallon': 27.3,
  'Number of cylinders': 4,
  'Displacement (cu in)': 79.0,
  'Gross horsepower': 66,
  'Rear axle ratio': 4.08,
  'Weight (1000 lbs)': 1.935,
  '1/4 mile time': 18.9,
  'Engine (0 = V-shaped, 1 = straight)': 1,
  'Transmission (0 = automatic, 1 = manual)': 1,
  'Number of forward gears': 4,
  'Number of carburetors': 1},
 {'Car Model ': 'Porsche 914-2',
  'Miles/(US) gallon': 26.0,
  'Number of cylinders': 4,
  'Displacement (cu in)': 120.3,
  'Gross horsepower': 91,
  'Rear axle ratio': 4.43,
  'Weight (1000 lbs)': 2.14,
  '1/4 mile time': 16.7,
  'Engine (0 = V-shaped, 1 = straight)': 0,
  'Transmission (0 = automatic, 1 = manual)': 1,
  'Number of forward gears': 5,
  'Number of carburetors': 2},
 {'Car Model ': 'Lotus Europa',
  'Miles/(US) gallon': 30.4,
  'Number of cylinders': 4,
  'Displacement (cu in)': 95.1,
  'Gross horsepower': 113,
  'Rear axle ratio': 3.77,
  'Weight (1000 lbs)': 1.513,
  '1/4 mile time': 16.9,
  'Engine (0 = V-shaped, 1 = straight)': 1,
  'Transmission (0 = automatic, 1 = manual)': 1,
  'Number of forward gears': 5,
  'Number of carburetors': 2},
 {'Car Model ': 'Ford Pantera L',
  'Miles/(US) gallon': 15.8,
  'Number of cylinders': 8,
  'Displacement (cu in)': 351.0,
  'Gross horsepower': 264,
  'Rear axle ratio': 4.22,
  'Weight (1000 lbs)': 3.17,
  '1/4 mile time': 14.5,
  'Engine (0 = V-shaped, 1 = straight)': 0,
  'Transmission (0 = automatic, 1 = manual)': 1,
  'Number of forward gears': 5,
  'Number of carburetors': 4},
 {'Car Model ': 'Ferrari Dino',
  'Miles/(US) gallon': 19.7,
  'Number of cylinders': 6,
  'Displacement (cu in)': 145.0,
  'Gross horsepower': 175,
  'Rear axle ratio': 3.62,
  'Weight (1000 lbs)': 2.77,
  '1/4 mile time': 15.5,
  'Engine (0 = V-shaped, 1 = straight)': 0,
  'Transmission (0 = automatic, 1 = manual)': 1,
  'Number of forward gears': 5,
  'Number of carburetors': 6},
 {'Car Model ': 'Maserati Bora',
  'Miles/(US) gallon': 15.0,
  'Number of cylinders': 8,
  'Displacement (cu in)': 301.0,
  'Gross horsepower': 335,
  'Rear axle ratio': 3.54,
  'Weight (1000 lbs)': 3.57,
  '1/4 mile time': 14.6,
  'Engine (0 = V-shaped, 1 = straight)': 0,
  'Transmission (0 = automatic, 1 = manual)': 1,
  'Number of forward gears': 5,
  'Number of carburetors': 8},
 {'Car Model ': 'Volvo 142E',
  'Miles/(US) gallon': 21.4,
  'Number of cylinders': 4,
  'Displacement (cu in)': 121.0,
  'Gross horsepower': 109,
  'Rear axle ratio': 4.11,
  'Weight (1000 lbs)': 2.78,
  '1/4 mile time': 18.6,
  'Engine (0 = V-shaped, 1 = straight)': 1,
  'Transmission (0 = automatic, 1 = manual)': 1,
  'Number of forward gears': 4,
  'Number of carburetors': 2}]

x=0
record = {
        'Car Model ': df['model'][x],
        'Miles/(US) gallon': df['mpg'][x],
        'Number of cylinders': df['cyl'][x],
        'Displacement (cu.in.)': df['disp'][x],
        'Gross horsepower': df['hp'][x],
        'Rear axle ratio': df['drat'][x],
        'Weight (1000 lbs)': df['wt'][x],
        '1/4 mile time': df['qsec'][x],
        'Engine (0 = V-shaped, 1 = straight)': df['vs'][x],
        'Transmission (0 = automatic, 1 = manual)': df['am'][x],
        'Number of forward gears': df['gear'][x],
        'Number of carburetors': df['carb'][x]
        }

In [26]:
record

{'_id': '1230',
 'Car Model ': 'Mazda RX4',
 'Miles/(US) gallon': 21.0,
 'Number of cylinders': 6,
 'Displacement (cu.in.)': 160.0,
 'Gross horsepower': 110,
 'Rear axle ratio': 3.9,
 'Weight (1000 lbs)': 2.62,
 '1/4 mile time': 16.46,
 'Engine (0 = V-shaped, 1 = straight)': 0,
 'Transmission (0 = automatic, 1 = manual)': 1,
 'Number of forward gears': 4,
 'Number of carburetors': 4}

In [16]:
information.insert_one(rec)